### ISSUE TITLE
Shipistrano ss4 support

### ISSUE THREAD

**Issue by adrexia** [dnadesign/dna-recipe#21]

**Comment by adrexia** [comment]
Pull request: https://github.com/dnadesign/shipistrano/pull/16

**Comment by Leapfrognz** [comment]
Might as well:
- Upgrade to Capistrano 3. #2 is ancient, no longer supported. Ive made a start on this but will take a while.
- Upgrade the slack helper to integrate with the proper slack API. 
- Add pre-deploy compile support, so you can gitignore your dist files and they build just before the cp from the local-cache to the server. The existing gulp/grunt tasks in the dna helpers rely on npm installing on the server itself... nightmare. Currently got this working on cap2 but its hacky
- Look at shipit (essentially a js version of cap) - Some interesting ideas there

**Comment by adrexia** [comment]
@Leapfrognz cap isn't my thing, so I went for the bare minimum this time. However, I agree.

**Comment by pitchandtone** [comment]
Merged
