### ISSUE TITLE
Linkable ss4 support

### ISSUE THREAD

**Issue by adrexia** [dnadesign/dna-recipe#22]
Test, log bugs, and help with updating https://github.com/sheadawson/silverstripe-linkable to work with Silverstripe 4. Update the recipe with any changes needed.

**Comment by adrexia** [comment]
Major changes have been proposed: https://github.com/sheadawson/silverstripe-linkable/issues/71  Originally in January though, so its hard to say how real they are.

**Comment by adrexia** [comment]
It also has DisplayLogic as a dependency, which will likely have some fairly major changes to work with 4.

**Comment by sminnee** [comment]
FYI – displaylogic SS4 compatibility PR in progress here. https://github.com/unclecheese/silverstripe-display-logic/pull/78

Any assistance with either of these much appreciated :-)

**Comment by adrexia** [comment]
Linkable is no longer maintained. Its now recomended we use:

[gorriecoe/silverstripe-link](https://github.com/gorriecoe/silverstripe-link)   
[gorriecoe/silverstripe-linkfield]( https://github.com/gorriecoe/silverstripe-linkfield) 
[silverstripe-embed](https://github.com/gorriecoe/silverstripe-embed)  

Closing this issue for now. We might decide to add (some of all of) the modules above to this recipe, but we'll need to trial them first.
